const assert=require('node:assert/strict');const {chromium}=require('playwright');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.goto('http://127.0.0.1:8765/');await page.addScriptTag({url:'/js/studio-autosave.js'});const result=await page.evaluate(async()=>{
const A=window.StudioAutosave,store=A.createIndexedDbStore(),bytes=async b=>Array.from(new Uint8Array(await b.arrayBuffer())),out=[];
const fixtures=[{name:'legacy',legacy:true,tracks:[{id:'v',gain:1,muted:false}],clips:[{id:'old',sourceId:'legacy-source',track:'v',start:0,trim:0,len:2,gain:1,muted:false}],sources:[{id:'legacy-source',data:[1,2,3]}]},{name:'multitrack',tracks:[{id:'v',gain:.8,muted:false},{id:'fx',gain:.5,muted:true}],clips:[{id:'moved',sourceId:'shared',track:'v',start:11,trim:.5,len:2,gain:.7,muted:false},{id:'split',sourceId:'shared',track:'v',start:13,trim:2,len:1,gain:.7,muted:false},{id:'duplicate',sourceId:'shared',track:'fx',start:15,trim:.5,len:2,gain:.4,muted:true},{id:'other',sourceId:'second',track:'fx',start:2,trim:0,len:4,gain:1,muted:false}],sources:[{id:'shared',data:[3,4,5]},{id:'second',data:[6,7,8]}]},{name:'long-mp3',tracks:[{id:'v',gain:1,muted:false}],clips:[{id:'long',sourceId:'long-source',track:'v',start:30,trim:0,len:900,gain:1,muted:false}],sources:[{id:'long-source',data:[73,68,51,4,0,0,0,0,0,0,1,2]}]}];
for(const f of fixtures){const projectId='id-'+f.name,snapshot={schema:f.legacy?1:2,name:f.name,tracks:f.tracks,clips:f.clips,cursor:4,zoom:2,selectionStart:1,selectionEnd:3},rows=f.sources.map(s=>({id:s.id,blob:new Blob([Uint8Array.from(s.data)],{type:'audio/mpeg'}),sourceSchema:f.legacy?1:2,mimeType:'audio/mpeg',originalName:s.id+'.mp3',origin:'phone-import'}));
if(f.legacy){await store.save(snapshot,rows);const m=await store.initializeLibrary({projectId});if(m.migrated?.id!==projectId)throw Error('legacy migration')}
else await store.createProject({id:projectId,name:f.name,snapshot,newSources:rows});
let opened=await store.openProject(projectId);if(opened.snapshot.projectId!==projectId)throw Error('projectId');await store.saveProject(projectId,opened.snapshot,[]);await store.closeProject();opened=await store.openProject(projectId);
if(JSON.stringify(opened.snapshot.clips)!==JSON.stringify(f.clips)||JSON.stringify(opened.snapshot.tracks)!==JSON.stringify(f.tracks))throw Error('metadata identity');
for(const s of f.sources){if(JSON.stringify(await bytes(opened.audio.get(s.id)))!==JSON.stringify(s.data))throw Error('blob identity '+s.id);if(opened.sources.get(s.id).id!==s.id)throw Error('source identity')}
const sidecar={sourceId:f.sources[0].id,engineVersion:'future',chunks:[{index:0,path:'derived-only'}]};if(!opened.snapshot.clips.some(c=>c.sourceId===sidecar.sourceId))throw Error('sidecar sourceId');if(Object.hasOwn(opened.snapshot,'chunkManifest'))throw Error('snapshot changed');out.push(f.name+':PASS')}
return{indexedDb:!!window.indexedDB,fixtures:out}});assert.equal(result.indexedDb,true);assert.equal(result.fixtures.length,3);console.log('REAL_INDEXEDDB=YES LEGACY_MIGRATION=PASS PROJECT_REOPEN=PASS METADATA_IDENTITY=PASS SOURCE_IDENTITY=PASS ORIGINAL_BLOBS_UNCHANGED=PASS SIDECAR_COMPATIBILITY=PASS '+result.fixtures.join(' '))}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
